apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  labels:
    app: zipkin
spec:
  type: LoadBalancer
  ports:
  - port: 9411
    targetPort: 9411
    protocol: TCP
  selector:
    app: zipkin